"""Add tasks table and update pomodoro session

Revision ID: a789b098de90
Revises: 6b177ba9f240
Create Date: 2026-03-21 17:22:54.058898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a789b098de90'
down_revision: Union[str, None] = '6b177ba9f240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
